Repository cjolowicz/cookiecutter-hypermodern-python, pull requests merged in 2020-10, with the labels that each got.

#584 Bump flake8 from 3.8.3 to 3.8.4
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: dependencies, python

#587 Bump virtualenv from 20.0.31 to 20.0.33 in /.github/workflows
  {{cookiecutter.project_name}}/.github/workflows/constraints.txt
Labels: dependencies, python

#590 Do not ignore missing type imports from pytest
  {{cookiecutter.project_name}}/mypy.ini
  {{cookiecutter.project_name}}/noxfile.py
Labels: bug

#585 Bump pytest from 6.1.0 to 6.1.1
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: dependencies, python

#588 Bump poetry from 1.0.10 to 1.1.2 in /.github/workflows
  {{cookiecutter.project_name}}/.github/workflows/constraints.txt
Labels: dependencies, python

#591 Ignore RST201 for compatibility with Google-style docstrings
  {{cookiecutter.project_name}}/.flake8
Labels: bug

#592 Bump prettier from 2.1.1 to 2.1.2
  {{cookiecutter.project_name}}/.pre-commit-config.yaml
Labels: dependencies

#593 Pin actions/upload-artifact to v2.2.0
  {{cookiecutter.project_name}}/.github/workflows/tests.yml
Labels: dependencies, github_actions

#594 Pin actions/cache to v2.1.1
  {{cookiecutter.project_name}}/.github/workflows/tests.yml
Labels: dependencies, github_actions

#586 Bump darglint from 1.5.4 to 1.5.5
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: dependencies, python

#595 Bump actions/setup-python from 2.1.2 to 2.1.3
  {{cookiecutter.project_name}}/.github/workflows/release.yml
  {{cookiecutter.project_name}}/.github/workflows/tests.yml
Labels: dependencies, github_actions

#596 Bump prettier from 2.1.1 to 2.1.2
  .pre-commit-config.yaml
Labels: cookiecutter, dependencies

#568 Combine coverage data with GitHub Action
  docs/guide.rst
  {{cookiecutter.project_name}}/.github/workflows/tests.yml
  {{cookiecutter.project_name}}/noxfile.py
Labels: bug

#598 Fix missing nox-poetry in Tests workflow
  {{cookiecutter.project_name}}/.github/workflows/tests.yml
Labels: bug

#601 Support `main` branch in Release workflow
  {{cookiecutter.project_name}}/.github/workflows/release.yml
Labels: bug

#599 Update documentation to Python 3.8.6
  docs/guide.rst
Labels: cookiecutter, documentation

#602 Use Read the Docs theme in local builds
  docs/guide.rst
  {{cookiecutter.project_name}}/docs/conf.py
  {{cookiecutter.project_name}}/docs/requirements.txt
  {{cookiecutter.project_name}}/noxfile.py
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: bug

#603 Support Python 3.9
  README.rst
  docs/guide.rst
  {{cookiecutter.project_name}}/.github/workflows/release.yml
  {{cookiecutter.project_name}}/.github/workflows/tests.yml
  {{cookiecutter.project_name}}/noxfile.py
  {{cookiecutter.project_name}}/pyproject.toml
Labels: enhancement

#605 Enable Nox session for xdoctest by default
  docs/guide.rst
  {{cookiecutter.project_name}}/.github/workflows/tests.yml
  {{cookiecutter.project_name}}/noxfile.py
Labels: enhancement

#606 Fix incomplete dependencies table in User Guide
  docs/guide.rst
Labels: documentation

#609 Minor improvements to the User Guide
  docs/guide.rst
Labels: documentation

#610 Remove references to master branch from documentation
  CONTRIBUTING.rst
  README.rst
  docs/guide.rst
Labels: documentation

#611 Move logo to docs/_static
  README.rst
  docs/_static/Logo.png
  docs/_static/logo.png
  docs/conf.py
Labels: cookiecutter, documentation

#614 Minor layout fix in User Guide
  docs/guide.rst
Labels: cookiecutter, documentation

#608 Generate command-line documentation with sphinx-click
  README.rst
  docs/guide.rst
  {{cookiecutter.project_name}}/README.rst
  {{cookiecutter.project_name}}/docs/conf.py
  {{cookiecutter.project_name}}/docs/index.rst
  {{cookiecutter.project_name}}/docs/requirements.txt
  {{cookiecutter.project_name}}/docs/usage.rst
  {{cookiecutter.project_name}}/noxfile.py
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: enhancement

#618 Bump actions/cache from v2.1.1 to v2.1.2
  {{cookiecutter.project_name}}/.github/workflows/tests.yml
Labels: dependencies, github_actions

#619 Bump mypy from 0.782 to 0.790
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: dependencies, python

#623 Bump virtualenv from 20.0.33 to 20.0.34 in /.github/workflows
  {{cookiecutter.project_name}}/.github/workflows/constraints.txt
Labels: dependencies, python

#626 Bump actions/setup-python from 2.1.3 to 2.1.4
  {{cookiecutter.project_name}}/.github/workflows/release.yml
  {{cookiecutter.project_name}}/.github/workflows/tests.yml
Labels: dependencies, github_actions

#625 Bump virtualenv from 20.0.34 to 20.0.35 in /.github/workflows
  {{cookiecutter.project_name}}/.github/workflows/constraints.txt
Labels: dependencies, python

#639 Update prettier hook to new pre-commit repo
  .pre-commit-config.yaml
  {{cookiecutter.project_name}}/.pre-commit-config.yaml
Labels: bug
