Repository cjolowicz/cookiecutter-hypermodern-python, pull requests merged in 2020-08, with the labels that each got.

#481 Bump coverage from 5.2 to 5.2.1
  {{cookiecutter.project_name}}/poetry.lock
Labels: dependencies, python

#482 Bump darglint from 1.5.1 to 1.5.2
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: dependencies, python

#483 Bump reorder-python-imports from 2.3.1 to 2.3.5
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: dependencies, python

#486 Bump virtualenv from 20.0.28 to 20.0.29 in /.github/workflows
  {{cookiecutter.project_name}}/.github/workflows/constraints.txt
Labels: dependencies, python

#485 Bump pytest from 5.4.3 to 6.0.1
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: dependencies, python

#484 Bump pre-commit-hooks from 3.1.0 to 3.2.0
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: dependencies, python

#487 Fix package installation in Nox sessions with non-final release versions
  {{cookiecutter.project_name}}/noxfile.py
Labels: bug

#489 Remove black nox session from documentation
  CONTRIBUTING.rst
  {{cookiecutter.project_name}}/CONTRIBUTING.rst
Labels: documentation

#490 Update CONTRIBUTORS.rst
  CONTRIBUTORS.rst
Labels: documentation

#488 Use Poetry to install core dependencies in Nox sessions
  {{cookiecutter.project_name}}/noxfile.py
Labels: enhancement

#491 Cache exported requirements in Nox sessions
  {{cookiecutter.project_name}}/noxfile.py
Labels: enhancement

#492 Do not install dependencies to Poetry environment from Nox session
  {{cookiecutter.project_name}}/noxfile.py
Labels: bug

#502 Bump virtualenv from 20.0.29 to 20.0.30 in /.github/workflows
  {{cookiecutter.project_name}}/.github/workflows/constraints.txt
Labels: dependencies, python

#503 Bump pip from 20.2 to 20.2.1 in /.github/workflows
  {{cookiecutter.project_name}}/.github/workflows/constraints.txt
Labels: dependencies, python

#504 Bump sphinx from 3.1.2 to 3.2.0 in /docs
  {{cookiecutter.project_name}}/docs/requirements.txt
Labels: dependencies, python

#505 Bump actions/checkout from v2.3.1 to v2.3.2
  {{cookiecutter.project_name}}/.github/workflows/release.yml
  {{cookiecutter.project_name}}/.github/workflows/tests.yml
Labels: dependencies, github_actions

#506 Bump sphinx from 3.1.2 to 3.2.0
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: dependencies, python

#507 Update documentation for Python 3.8.5
  docs/guide.rst
Labels: cookiecutter, documentation

#508 Bump pip from 20.2 to 20.2.2 in /.github/workflows
  {{cookiecutter.project_name}}/.github/workflows/constraints.txt
Labels: dependencies, python

#511 Bump actions/setup-python from v2.1.1 to v2.1.2
  {{cookiecutter.project_name}}/.github/workflows/release.yml
  {{cookiecutter.project_name}}/.github/workflows/tests.yml
Labels: dependencies, github_actions

#498 Add docs-build session
  .github/workflows/tests.yml
  docs/guide.rst
  {{cookiecutter.project_name}}/.github/workflows/tests.yml
  {{cookiecutter.project_name}}/noxfile.py
Labels: enhancement
