Repository cjolowicz/cookiecutter-hypermodern-python, pull requests merged in 2020-11, with the labels that each got.

#638 Change to standalone build backend (PEP-517)
  {{cookiecutter.project_name}}/pyproject.toml
Labels: bug

#650 Bump codecov/codecov-action from v1.0.13 to v1.0.14
  {{cookiecutter.project_name}}/.github/workflows/tests.yml
Labels: dependencies, github_actions

#651 Bump pip from 20.2.3 to 20.2.4 in /.github/workflows
  {{cookiecutter.project_name}}/.github/workflows/constraints.txt
Labels: dependencies, python

#653 Bump release-drafter/release-drafter from v5.11.0 to v5.12.1
  {{cookiecutter.project_name}}/.github/workflows/release.yml
Labels: dependencies, github_actions

#655 Bump virtualenv from 20.0.35 to 20.1.0 in /.github/workflows
  {{cookiecutter.project_name}}/.github/workflows/constraints.txt
Labels: dependencies, python

#656 Bump pygments from 2.7.1 to 2.7.2
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: dependencies, python

#659 Bump sphinx from 3.2.1 to 3.3.0 in /docs
  {{cookiecutter.project_name}}/docs/requirements.txt
Labels: dependencies, python

#654 Bump pre-commit-hooks from 3.2.0 to 3.3.0
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: dependencies, python

#657 Bump pytest from 6.1.1 to 6.1.2
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: dependencies, python

#658 Bump pre-commit from 2.7.1 to 2.8.2
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: dependencies, python

#660 Pin pre-commit to 2.8.2 in .github/workflows/constraints.txt
  .github/workflows/constraints.txt
Labels: cookiecutter, dependencies, python

#642 Upgrade Ubuntu version in guide
  docs/guide.rst
Labels: documentation

#631 Support packages whose name does not match the project name
  {{cookiecutter.project_name}}/pyproject.toml
Labels: enhancement

#663 Bump reorder-python-imports from 2.3.5 to 2.3.6
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: dependencies, python

#662 Update actions/checkout requirement to v2.3.4
  {{cookiecutter.project_name}}/.github/workflows/release.yml
  {{cookiecutter.project_name}}/.github/workflows/tests.yml
Labels: dependencies, github_actions

#664 Bump sphinx from 3.2.1 to 3.3.0
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: dependencies, python

#634 Add GitHub Labeler Action to manage project labels automatically
  .github/labels.yml
  .github/workflows/labeler.yml
  README.rst
  docs/guide.rst
  {{cookiecutter.project_name}}/.github/labels.yml
  {{cookiecutter.project_name}}/.github/workflows/labeler.yml
Labels: enhancement

#667 Bump regex from 2020.6.8 to 2020.10.28
  {{cookiecutter.project_name}}/poetry.lock
Labels: dependencies, python

#668 Bump actions/cache from v2.1.2 to v2.1.3
  {{cookiecutter.project_name}}/.github/workflows/tests.yml
Labels: dependencies, github_actions

#671 Bump sphinx from 3.3.0 to 3.3.1
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: dependencies, python

#670 Bump sphinx from 3.3.0 to 3.3.1 in /docs
  {{cookiecutter.project_name}}/docs/requirements.txt
Labels: dependencies, python

#672 Release 2020.11.15
  README.rst
  docs/guide.rst
  docs/index.rst
Labels: documentation

#673 Remove Quickstart from README
  README.rst
  docs/guide.rst
  docs/quickstart.rst
Labels: cookiecutter, documentation
