Repository cjolowicz/cookiecutter-hypermodern-python, pull requests merged in 2020-07, with the labels that each got.

#427 Update documentation for Python 3.7.8 and 3.6.11
  docs/guide.rst
Labels: documentation

#422 Bump importlib-resources from 2.0.1 to 3.0.0
  {{cookiecutter.project_name}}/poetry.lock
Labels: dependencies, python

#423 Bump identify from 1.4.20 to 1.4.21
  {{cookiecutter.project_name}}/poetry.lock
Labels: dependencies, python

#424 Bump idna from 2.9 to 2.10
  {{cookiecutter.project_name}}/poetry.lock
Labels: dependencies, python

#425 Bump importlib-metadata from 1.6.1 to 1.7.0
  {{cookiecutter.project_name}}/poetry.lock
Labels: dependencies, python

#426 Bump distlib from 0.3.0 to 0.3.1
  {{cookiecutter.project_name}}/poetry.lock
Labels: dependencies, python

#430 Bump pre-commit from 2.5.1 to 2.6.0
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: dependencies, python

#436 Bump virtualenv from 20.0.25 to 20.0.26
  {{cookiecutter.project_name}}/poetry.lock
Labels: dependencies, python

#437 Bump coverage from 5.1 to 5.2
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: dependencies, python

#439 Bump sphinx from 3.1.1 to 3.1.2 in /docs
  {{cookiecutter.project_name}}/docs/requirements.txt
Labels: dependencies, python

#438 Bump sphinx from 3.1.1 to 3.1.2
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: dependencies, python

#402 Upgrade to GitHub Dependabot
  README.rst
  docs/guide.rst
  {{cookiecutter.project_name}}/.dependabot/config.yml
  {{cookiecutter.project_name}}/.github/dependabot.yml
Labels: ci, enhancement

#441 Bump virtualenv from 20.0.21 to 20.0.26 in /.github/workflows
  {{cookiecutter.project_name}}/.github/workflows/constraints.txt
Labels: dependencies, python

#442 Bump pypa/gh-action-pypi-publish from v1.2.2 to v1.3.1
  {{cookiecutter.project_name}}/.github/workflows/release.yml
Labels: dependencies, github_actions

#444 Bump codecov/codecov-action from v1.0.7 to v1.0.10
  {{cookiecutter.project_name}}/.github/workflows/tests.yml
Labels: dependencies, github_actions

#443 Bump actions/checkout from v2.2.0 to v2.3.1
  {{cookiecutter.project_name}}/.github/workflows/release.yml
  {{cookiecutter.project_name}}/.github/workflows/tests.yml
Labels: dependencies, github_actions

#397 Track pre-commit hooks as Poetry dependencies
  docs/guide.rst
  {{cookiecutter.project_name}}/.pre-commit-config.yaml
  {{cookiecutter.project_name}}/noxfile.py
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: enhancement

#451 Bump darglint from 1.4.1 to 1.5.1
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: dependencies, python

#449 Update documentation for Python 3.8.4
  docs/guide.rst
Labels: documentation

#447 Bump salsify/action-detect-and-tag-new-version from v1.0.3 to v2.0.1
  {{cookiecutter.project_name}}/.github/workflows/release.yml
Labels: dependencies, github_actions

#448 Bump xdoctest from 0.12.0 to 0.13.0
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: dependencies, python

#452 Bump pep8-naming from 0.10.0 to 0.11.1
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: dependencies, python

#454 Release 2020.7.15
  README.rst
  docs/guide.rst
  docs/index.rst
Labels: documentation

#455 Remove Dependabot badge
  README.rst
  {{cookiecutter.project_name}}/README.rst
Labels: documentation

#457 Bump virtualenv from 20.0.26 to 20.0.27 in /.github/workflows
  {{cookiecutter.project_name}}/.github/workflows/constraints.txt
Labels: dependencies, python

#458 Advertise a monthly release cadence
  docs/guide.rst
Labels: cookiecutter, documentation

#459 Reorder sections in mypy.ini
  {{cookiecutter.project_name}}/mypy.ini
Labels: refactoring

#467 Bump poetry from 1.0.9 to 1.0.10 in /.github/workflows
  {{cookiecutter.project_name}}/.github/workflows/constraints.txt
Labels: dependencies, python

#466 Bump reorder-python-imports from 2.3.1 to 2.3.2
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: dependencies, python

#475 Fix reversal of "kebab case" and "snake case" in User Guide
  docs/guide.rst
Labels: documentation

#477 Bump actions/setup-python from v2 to v2.1.1
  {{cookiecutter.project_name}}/.github/workflows/release.yml
  {{cookiecutter.project_name}}/.github/workflows/tests.yml
Labels: dependencies, github_actions

#478 Bump codecov/codecov-action from v1.0.10 to v1.0.12
  {{cookiecutter.project_name}}/.github/workflows/tests.yml
Labels: dependencies, github_actions

#479 Bump virtualenv from 20.0.27 to 20.0.28 in /.github/workflows
  {{cookiecutter.project_name}}/.github/workflows/constraints.txt
Labels: dependencies, python

#480 Bump pip from 20.1.1 to 20.2 in /.github/workflows
  {{cookiecutter.project_name}}/.github/workflows/constraints.txt
Labels: dependencies, python
