Repository cjolowicz/cookiecutter-hypermodern-python, pull requests merged in 2020-05, with the labels that each got.

#214 Add custom stylesheet for Cookiecutter documentation
  README.rst
  docs/_static/custom.css
  docs/guide.rst
Labels: documentation

#215 Minor documentation improvements
  README.rst
  docs/guide.rst
Labels: documentation

#216 Add overview of generated files to documentation
  docs/guide.rst
Labels: documentation

#218 Clean up references in documentation
  CONTRIBUTING.rst
  README.rst
  docs/guide.rst
  docs/index.rst
Labels: documentation

#219 Configure Sphinx language to "en"
  docs/conf.py
Labels: documentation

#226 Display table captions like admonition titles
  docs/_static/custom.css
  noxfile.py
Labels: documentation

#228 Remove flake8-import-order
  docs/guide.rst
  {{cookiecutter.project_name}}/.flake8
  {{cookiecutter.project_name}}/noxfile.py
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: removal

#227 Sort imports with reorder-python-imports
  docs/guide.rst
  {{cookiecutter.project_name}}/.pre-commit-config.yaml
  {{cookiecutter.project_name}}/noxfile.py
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
  {{cookiecutter.project_name}}/tests/test_main.py
Labels: enhancement

#232 Ignore .mypy_cache/ in subdirectories
  {{cookiecutter.project_name}}/.gitignore
Labels: style

#233 Add Nox session for pre-commit
  docs/guide.rst
  {{cookiecutter.project_name}}/noxfile.py
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: enhancement

#237 Minor documentation fix
  docs/guide.rst
Labels: documentation

#231 Use official pre-commit hooks instead of repository-local hooks
  docs/guide.rst
  {{cookiecutter.project_name}}/.pre-commit-config.yaml
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: enhancement

#234 Remove pre-commit hook for mypy
  docs/guide.rst
  {{cookiecutter.project_name}}/.pre-commit-config.yaml
Labels: removal

#235 Remove Nox session for Black
  docs/guide.rst
  {{cookiecutter.project_name}}/noxfile.py
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: removal

#236 Remove Nox session for Flake8
  docs/guide.rst
  {{cookiecutter.project_name}}/.flake8
  {{cookiecutter.project_name}}/noxfile.py
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: removal

#243 Run pre-commit from Nox and Tests workflow
  docs/guide.rst
  {{cookiecutter.project_name}}/.github/workflows/release.yml
  {{cookiecutter.project_name}}/.github/workflows/tests.yml
  {{cookiecutter.project_name}}/noxfile.py
Labels: ci

#244 Remove the pre-commit workflow
  docs/guide.rst
  {{cookiecutter.project_name}}/.github/workflows/constraints.txt
  {{cookiecutter.project_name}}/.github/workflows/pre-commit.yml
Labels: removal

#240 Update and rework the documentation
  README.rst
  docs/_static/custom.css
  docs/guide.rst
Labels: documentation

#255 Fix missing type information in mypy session
  {{cookiecutter.project_name}}/noxfile.py
Labels: bug

#259 Use Dependabot for dependencies in template directory
  .dependabot/config.yml
Labels: ci

#263 Do not cache pre-commit environments on Windows
  .github/workflows/pre-commit.yml
  .github/workflows/tests.yml
  {{cookiecutter.project_name}}/.github/workflows/release.yml
  {{cookiecutter.project_name}}/.github/workflows/tests.yml
Labels: bug, ci

#266 Remove redundant pre-commit step in Tests workflow (Cookiecutter)
  .github/workflows/constraints.txt
  .github/workflows/tests.yml
Labels: ci

#225 Upgrade dependencies
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: dependencies

#268 Bump pip from 20.0.2 to 20.1
  .github/workflows/constraints.txt
  {{cookiecutter.project_name}}/.github/workflows/constraints.txt
Labels: dependencies

#272 Bump toml from 0.10.0 to 0.10.1
  {{cookiecutter.project_name}}/poetry.lock
Labels: dependencies

#275 Bump actions/setup-python from v1.2.0 to v2
  {{cookiecutter.project_name}}/.github/workflows/coverage.yml
  {{cookiecutter.project_name}}/.github/workflows/docs.yml
  {{cookiecutter.project_name}}/.github/workflows/release.yml
  {{cookiecutter.project_name}}/.github/workflows/test-pypi.yml
  {{cookiecutter.project_name}}/.github/workflows/tests.yml
Labels: dependencies

#273 Bump pre-commit-hooks from v2.5.0 to v3.0.0
  .pre-commit-config.yaml
  {{cookiecutter.project_name}}/.pre-commit-config.yaml
Labels: dependencies

#278 Revert "Use Dependabot for dependencies in template directory (#259)"
  .dependabot/config.yml
Labels: ci

#277 Bump darglint from 1.2.3 to 1.3.0
  {{cookiecutter.project_name}}/.pre-commit-config.yaml
Labels: dependencies

#279 Bump release-drafter/release-drafter from v5.7.0 to v5.8.0
  .github/workflows/release-drafter.yml
  {{cookiecutter.project_name}}/.github/workflows/release-drafter.yml
Labels: dependencies

#280 Bump codecov/codecov-action from v1.0.6 to v1.0.7
  {{cookiecutter.project_name}}/.github/workflows/coverage.yml
Labels: dependencies

#281 Bump actions/upload-artifact from v1.0.0 to v2
  .github/workflows/docs.yml
  {{cookiecutter.project_name}}/.github/workflows/docs.yml
Labels: dependencies

#276 Bump actions/cache from v1.1.2 to v1.2.0
  .github/workflows/pre-commit.yml
  .github/workflows/tests.yml
  {{cookiecutter.project_name}}/.github/workflows/release.yml
  {{cookiecutter.project_name}}/.github/workflows/tests.yml
Labels: dependencies

#282 Bump flake8 from 3.7.9 to 3.8.1
  {{cookiecutter.project_name}}/.pre-commit-config.yaml
Labels: dependencies

#285 Remove Python < 3.8 checks on macOS and Windows
  .github/workflows/tests.yml
  {{cookiecutter.project_name}}/.github/workflows/tests.yml
Labels: ci

#286 Do not fail fast in Tests workflow
  .github/workflows/tests.yml
  {{cookiecutter.project_name}}/.github/workflows/tests.yml
Labels: ci

#283 Bump actions/setup-python from v1.2.0 to v2
  .github/workflows/docs.yml
  .github/workflows/pre-commit.yml
  .github/workflows/reset-instance.yml
  .github/workflows/tests.yml
Labels: dependencies

#287 Run pre-commit only on Ubuntu (Cookiecutter)
  .github/workflows/pre-commit.yml
Labels: ci

#289 Fix template URL in Reset Instance workflow
  .github/workflows/reset-instance.yml
Labels: ci

#291 Trigger checks on pull requests
  .github/workflows/docs.yml
  .github/workflows/pre-commit.yml
  .github/workflows/tests.yml
  docs/guide.rst
  {{cookiecutter.project_name}}/.github/workflows/coverage.yml
  {{cookiecutter.project_name}}/.github/workflows/docs.yml
  {{cookiecutter.project_name}}/.github/workflows/tests.yml
Labels: ci

#222 Added toml-check hook to pre-commit
  docs/guide.rst
  {{cookiecutter.project_name}}/.pre-commit-config.yaml
Labels: enhancement

#294 Add CONTRIBUTORS.rst
  CONTRIBUTORS.rst
  docs/contributors.rst
  docs/index.rst
Labels: documentation

#293 Expand generated README.rst
  CONTRIBUTING.rst
  docs/contributing.rst
  {{cookiecutter.project_name}}/CONTRIBUTING.rst
  {{cookiecutter.project_name}}/README.rst
  {{cookiecutter.project_name}}/docs/contributing.rst
  {{cookiecutter.project_name}}/docs/index.rst
Labels: documentation

#295 Fix reST headings in generated documentation
  {{cookiecutter.project_name}}/README.rst
  {{cookiecutter.project_name}}/docs/reference.rst
Labels: documentation

#297 Do not underline badges in Sphinx documentation
  docs/_static/custom.css
Labels: documentation

#101 Release 2020.5.15
  README.rst
  docs/guide.rst
  docs/index.rst
Labels: documentation

#299 Publish release when version changes on master branch
  README.rst
  docs/guide.rst
  {{cookiecutter.project_name}}/.github/workflows/release-drafter.yml
  {{cookiecutter.project_name}}/.github/workflows/release.yml
  {{cookiecutter.project_name}}/.github/workflows/test-pypi.yml
Labels: ci

#300 Simplify Jinja escapes in Tests workflow
  {{cookiecutter.project_name}}/.github/workflows/tests.yml
Labels: ci

#301 Refactor the Tests workflow
  {{cookiecutter.project_name}}/.github/workflows/tests.yml
Labels: ci

#303 Remove some non-Linux and older Python checks
  docs/guide.rst
  {{cookiecutter.project_name}}/.github/workflows/tests.yml
Labels: ci

#304 Merge Docs workflow into Tests workflow
  docs/guide.rst
  {{cookiecutter.project_name}}/.github/workflows/docs.yml
  {{cookiecutter.project_name}}/.github/workflows/tests.yml
Labels: ci

#306 Bump more-itertools from 8.2.0 to 8.3.0
  {{cookiecutter.project_name}}/poetry.lock
Labels: dependencies

#307 Fix missing underlines on some links
  docs/_static/custom.css
  docs/index.rst
Labels: documentation

#308 Move CI status badges to the end
  README.rst
Labels: documentation

#311 Remove pytest-cov
  docs/guide.rst
  {{cookiecutter.project_name}}/noxfile.py
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: removal

#313 Do not restore pre-commit cache in non-pre-commit jobs
  {{cookiecutter.project_name}}/.github/workflows/tests.yml
Labels: ci

#314 Remove */site-packages path prefix from coverage report
  {{cookiecutter.project_name}}/noxfile.py
Labels: style

#321 Fix documented Python versions for pre-commit session
  docs/guide.rst
Labels: documentation

#322 Only run the targeted Python version in each CI job
  {{cookiecutter.project_name}}/.github/workflows/tests.yml
Labels: ci

#318 Bump actions/checkout from v2.1.0 to v2.1.1
  {{cookiecutter.project_name}}/.github/workflows/coverage.yml
  {{cookiecutter.project_name}}/.github/workflows/release.yml
  {{cookiecutter.project_name}}/.github/workflows/tests.yml
Labels: dependencies

#312 Produce a single combined coverage report for all Python versions
  docs/guide.rst
  {{cookiecutter.project_name}}/noxfile.py
Labels: testing

#315 Allow coverage session to be run stand-alone
  docs/guide.rst
  {{cookiecutter.project_name}}/noxfile.py
Labels: testing

#325 Adapt Coverage workflow to use coverage session
  docs/guide.rst
  {{cookiecutter.project_name}}/.github/workflows/coverage.yml
Labels: ci

#326 Bump virtualenv from 20.0.20 to 20.0.21
  {{cookiecutter.project_name}}/poetry.lock
Labels: dependencies

#327 Bump packaging from 20.3 to 20.4
  {{cookiecutter.project_name}}/poetry.lock
Labels: dependencies

#328 Merge Coverage workflow into Tests workflow
  docs/guide.rst
  {{cookiecutter.project_name}}/.github/workflows/coverage.yml
  {{cookiecutter.project_name}}/.github/workflows/tests.yml
Labels: ci

#330 Pin virtualenv to 20.0.21
  docs/guide.rst
  {{cookiecutter.project_name}}/.github/workflows/constraints.txt
Labels: ci

#329 Add overview of GitHub Actions
  docs/guide.rst
Labels: documentation

#331 Bump identify from 1.4.15 to 1.4.16
  {{cookiecutter.project_name}}/poetry.lock
Labels: dependencies

#332 Bump six from 1.14.0 to 1.15.0
  {{cookiecutter.project_name}}/poetry.lock
Labels: dependencies

#340 Do not skip coverage session when tests fail
  {{cookiecutter.project_name}}/noxfile.py
Labels: bug
