Repository cjolowicz/cookiecutter-hypermodern-python, pull requests merged in 2020-03, with the labels that each got.

#52 Add Prettier pre-commit hook
  .github/release-drafter.yml
  .github/workflows/tests.yml
  CODE_OF_CONDUCT.md
  README.md
  {{cookiecutter.project_name}}/.github/release-drafter.yml
  {{cookiecutter.project_name}}/.github/workflows/coverage.yml
  {{cookiecutter.project_name}}/.github/workflows/release.yml
  {{cookiecutter.project_name}}/.github/workflows/test-pypi.yml
  {{cookiecutter.project_name}}/.github/workflows/tests.yml
  {{cookiecutter.project_name}}/.pre-commit-config.yaml
  {{cookiecutter.project_name}}/CODE_OF_CONDUCT.md
Labels: enhancement

#61 Minor fixes to README.md
  README.md
Labels: documentation

#64 Use PyPA action for uploading to PyPI
  {{cookiecutter.project_name}}/.github/workflows/release.yml
  {{cookiecutter.project_name}}/.github/workflows/test-pypi.yml
Labels: ci

#63 Upgrade to Poetry 1.0.5
  {{cookiecutter.project_name}}/.github/workflows/coverage.yml
  {{cookiecutter.project_name}}/.github/workflows/release.yml
  {{cookiecutter.project_name}}/.github/workflows/test-pypi.yml
  {{cookiecutter.project_name}}/.github/workflows/tests.yml
Labels: ci

#37 Upgrade dependencies
  {{cookiecutter.project_name}}/docs/requirements.txt
  {{cookiecutter.project_name}}/poetry.lock
Labels: build

#65 Use GitHub Action from Codecov
  {{cookiecutter.project_name}}/.github/workflows/coverage.yml
  {{cookiecutter.project_name}}/noxfile.py
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: ci

#66 Upgrade dependencies
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: build

#67 Adapt README.md after adding Prettier and the Codecov Action
  README.md
Labels: documentation

#68 Upgrade dependencies
  {{cookiecutter.project_name}}/poetry.lock
Labels: build

#69 Upgrade hooks
  {{cookiecutter.project_name}}/.pre-commit-config.yaml
Labels: build

#70 Add flake8-rst-docstrings to linting rules
  README.md
  {{cookiecutter.project_name}}/.flake8
  {{cookiecutter.project_name}}/noxfile.py
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: enhancement

#36 Add CalVer badge
  README.md
Labels: documentation
