Repository cjolowicz/cookiecutter-hypermodern-python, pull requests merged in 2020-06, with the labels that each got.

#341 Bump nox from 2019.11.9 to 2020.5.24
  {{cookiecutter.project_name}}/.github/workflows/constraints.txt
Labels: dependencies

#351 Bump sphinx from 3.0.3 to 3.0.4
  {{cookiecutter.project_name}}/docs/requirements.txt
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: dependencies

#352 Bump nodeenv from 1.3.5 to 1.4.0
  {{cookiecutter.project_name}}/poetry.lock
Labels: dependencies

#354 Bump wcwidth from 0.1.9 to 0.2.3
  {{cookiecutter.project_name}}/poetry.lock
Labels: dependencies

#357 Bump identify from 1.4.16 to 1.4.19
  {{cookiecutter.project_name}}/poetry.lock
Labels: dependencies

#358 Bump nox from 2019.11.9 to 2020.5.24
  .github/workflows/constraints.txt
Labels: cookiecutter, dependencies

#359 Pin virtualenv to 20.0.21
  .github/workflows/constraints.txt
Labels: cookiecutter, dependencies

#343 Use nox --python instead of session suffixes in Tests workflow
  {{cookiecutter.project_name}}/.github/workflows/tests.yml
Labels: ci

#353 Bump typeguard from 2.7.1 to 2.8.0
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: dependencies

#355 Bump pytest from 5.4.2 to 5.4.3
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: dependencies

#356 Bump mypy from 0.770 to 0.780
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: dependencies

#360 Bump typeguard from 2.8.0 to 2.9.0
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: dependencies

#370 Bump sphinx from 3.0.4 to 3.1.0
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: dependencies

#371 Bump pre-commit from 2.4.0 to 2.5.1
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: dependencies

#342 Type-check noxfile.py
  {{cookiecutter.project_name}}/mypy.ini
  {{cookiecutter.project_name}}/noxfile.py
Labels: enhancement

#376 Update documentation for Python 3.8.3
  docs/guide.rst
Labels: documentation

#378 Fix leading blank line in README and API reference
  {{cookiecutter.project_name}}/README.rst
  {{cookiecutter.project_name}}/docs/reference.rst
Labels: documentation

#381 Bump pre-commit-hooks from v3.0.0 to v3.1.0
  {{cookiecutter.project_name}}/.pre-commit-config.yaml
Labels: dependencies

#382 Bump pypa/gh-action-pypi-publish from v1.1.0 to v1.2.2
  {{cookiecutter.project_name}}/.github/workflows/release.yml
Labels: dependencies

#383 Bump pre-commit-hooks from v3.0.0 to v3.1.0
  .pre-commit-config.yaml
Labels: cookiecutter, dependencies

#385 Bump flake8 from v3.8.1 to v3.8.3
  {{cookiecutter.project_name}}/.pre-commit-config.yaml
Labels: dependencies

#387 Bump actions/checkout from v2.1.1 to v2.2.0
  .github/workflows/docs.yml
  .github/workflows/pre-commit.yml
  .github/workflows/reset-instance.yml
  .github/workflows/tests.yml
Labels: cookiecutter, dependencies

#389 Bump actions/cache from v1.2.0 to v2.0.0
  .github/workflows/pre-commit.yml
  .github/workflows/tests.yml
Labels: cookiecutter, dependencies

#391 Bump release-drafter/release-drafter from v5.8.0 to v5.11.0
  .github/workflows/release-drafter.yml
Labels: cookiecutter, dependencies

#392 Bump poetry from 1.0.5 to 1.0.9
  .github/workflows/constraints.txt
Labels: cookiecutter, dependencies

#394 Enable runtime type-checking with Typeguard by default
  docs/guide.rst
  {{cookiecutter.project_name}}/.github/workflows/tests.yml
  {{cookiecutter.project_name}}/noxfile.py
Labels: enhancement

#384 Bump poetry from 1.0.5 to 1.0.9 in /.github/workflows
  {{cookiecutter.project_name}}/.github/workflows/constraints.txt
Labels: dependencies

#386 Bump darglint from 1.3.0 to 1.4.1
  {{cookiecutter.project_name}}/.pre-commit-config.yaml
Labels: dependencies

#388 Bump actions/checkout from v2.1.1 to v2.2.0
  {{cookiecutter.project_name}}/.github/workflows/release.yml
  {{cookiecutter.project_name}}/.github/workflows/tests.yml
Labels: dependencies

#390 Bump release-drafter/release-drafter from v5.8.0 to v5.11.0
  {{cookiecutter.project_name}}/.github/workflows/release.yml
Labels: dependencies

#393 Bump actions/cache from v1.2.0 to v2
  {{cookiecutter.project_name}}/.github/workflows/tests.yml
Labels: dependencies

#395 Add badge with development status alpha
  README.rst
Labels: cookiecutter, documentation

#398 Release 2020.6.15
  README.rst
  docs/guide.rst
Labels: documentation

#407 Fix stale version in Sphinx documentation
  docs/index.rst
Labels: documentation

#404 Organize badges in multiple rows
  README.rst
  {{cookiecutter.project_name}}/README.rst
Labels: documentation

#410 Bump watchdog from 0.10.2 to 0.10.3
  {{cookiecutter.project_name}}/poetry.lock
Labels: dependencies, python

#411 Bump py from 1.8.1 to 1.9.0
  {{cookiecutter.project_name}}/poetry.lock
Labels: dependencies, python

#412 Bump virtualenv from 20.0.21 to 20.0.25
  {{cookiecutter.project_name}}/poetry.lock
Labels: dependencies, python

#413 Bump wcwidth from 0.2.4 to 0.2.5
  {{cookiecutter.project_name}}/poetry.lock
Labels: dependencies, python

#414 Bump mypy from 0.780 to 0.782
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: dependencies, python

#415 Bump identify from 1.4.19 to 1.4.20
  {{cookiecutter.project_name}}/poetry.lock
Labels: dependencies, python

#416 Bump certifi from 2020.4.5.2 to 2020.6.20
  {{cookiecutter.project_name}}/poetry.lock
Labels: dependencies, python

#418 Bump more-itertools from 8.3.0 to 8.4.0
  {{cookiecutter.project_name}}/poetry.lock
Labels: dependencies, python

#417 Bump requests from 2.23.0 to 2.24.0
  {{cookiecutter.project_name}}/poetry.lock
Labels: dependencies, python

#420 Bump importlib-resources from 1.5.0 to 2.0.1
  {{cookiecutter.project_name}}/poetry.lock
Labels: dependencies, python

#419 Bump sphinx from 3.1.0 to 3.1.1
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: dependencies, python

#421 Bump sphinx from 3.1.0 to 3.1.1 in /docs
  {{cookiecutter.project_name}}/docs/requirements.txt
Labels: dependencies, python
