Repository cjolowicz/cookiecutter-hypermodern-python, pull requests merged in 2021-06, with the labels that each got.

#904 Bump virtualenv from 20.4.4 to 20.4.6 in /.github/workflows
  {{cookiecutter.project_name}}/.github/workflows/constraints.txt
Labels: dependencies, python

#646 Bump docs and docs-build session python to 3.9
  docs/guide.rst
  {{cookiecutter.project_name}}/.github/workflows/tests.yml
  {{cookiecutter.project_name}}/noxfile.py
Labels: dependencies

#921 Bump typeguard from 2.12.0 to 2.12.1
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: dependencies, python

#924 Bump virtualenv from 20.4.4 to 20.4.7 in /.github/workflows
  {{cookiecutter.project_name}}/.github/workflows/constraints.txt
Labels: dependencies, python

#926 Bump pip from 21.1.1 to 21.1.2 in /.github/workflows
  {{cookiecutter.project_name}}/.github/workflows/constraints.txt
Labels: dependencies, python

#920 Bump codecov/codecov-action from 1.5.0 to 1.5.2
  {{cookiecutter.project_name}}/.github/workflows/tests.yml
Labels: dependencies, github_actions

#923 Bump actions/cache from 2.1.5 to 2.1.6
  {{cookiecutter.project_name}}/.github/workflows/tests.yml
Labels: dependencies, github_actions

#927 Bump sphinx from 3.5.4 to 4.0.2 in /docs
  {{cookiecutter.project_name}}/docs/requirements.txt
Labels: dependencies, python

#936 Bump nox from 2020.12.31 to 2021.6.12 in /.github/workflows
  {{cookiecutter.project_name}}/.github/workflows/constraints.txt
Labels: dependencies, python

#938 Bump sphinx-click from 2.7.1 to 3.0.1
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: dependencies, python

#939 Bump sphinx-click from 2.7.1 to 3.0.1 in /docs
  {{cookiecutter.project_name}}/docs/requirements.txt
Labels: dependencies, python

#940 Bump nox-poetry from 0.8.5 to 0.8.6 in /.github/workflows
  {{cookiecutter.project_name}}/.github/workflows/constraints.txt
Labels: dependencies, python

#941 Bump sphinx from 3.5.4 to 4.0.2
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: dependencies, python

#931 Bump actions/checkout from 2.3.3 to 2.3.4
  {{cookiecutter.project_name}}/.github/workflows/labeler.yml
Labels: dependencies, github_actions

#944 Bump click from 7.1.2 to 8.0.1
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: dependencies, python

#943 Simplify Nox session for code coverage
  {{cookiecutter.project_name}}/noxfile.py
Labels: ci

#945 Bump click from 7.1.2 to 8.0.1 in poetry.lock
  {{cookiecutter.project_name}}/poetry.lock
Labels: dependencies, python

#932 Bump flake8 from 3.9.1 to 3.9.2
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: dependencies, python

#937 Bump mypy from 0.812 to 0.902
  {{cookiecutter.project_name}}/noxfile.py
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
  {{cookiecutter.project_name}}/src/{{cookiecutter.package_name}}/__main__.py
Labels: dependencies, python

#925 Bump pre-commit from 2.12.1 to 2.13.0
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: dependencies, python

#928 Bump pre-commit-hooks from 3.4.0 to 4.0.1
  {{cookiecutter.project_name}}/poetry.lock
  {{cookiecutter.project_name}}/pyproject.toml
Labels: dependencies, python

#675 Add label skip-changelog for excluding PRs from release notes
  .github/labels.yml
  .github/release-drafter.yml
Labels: ci, cookiecutter

#947 Require click 8.x
  {{cookiecutter.project_name}}/pyproject.toml
Labels: dependencies, python

#935 Move `mypy` configuration into `pyproject.toml`
  docs/guide.rst
  {{cookiecutter.project_name}}/mypy.ini
  {{cookiecutter.project_name}}/pyproject.toml
Labels: ci

#948 Update CONTRIBUTORS.rst
  CONTRIBUTORS.rst
Labels: documentation

#949 Release 2021.6.15
  README.rst
  docs/guide.rst
  docs/index.rst
  docs/quickstart.rst
Labels: cookiecutter, documentation, skip-changelog

#950 Remove reference to mypy.ini from User Guide
  docs/guide.rst
Labels: documentation

#951 Update poetry.lock
  {{cookiecutter.project_name}}/poetry.lock
Labels: build

#952 Remove types-click from Nox session for mypy
  {{cookiecutter.project_name}}/noxfile.py
  {{cookiecutter.project_name}}/src/{{cookiecutter.package_name}}/__main__.py
Labels: testing

#953 Release 2021.6.16
  README.rst
  docs/guide.rst
  docs/index.rst
  docs/quickstart.rst
Labels: cookiecutter, documentation, skip-changelog
