Repository cjolowicz/cookiecutter-hypermodern-python, pull requests merged in 2022-02, with the labels that each got.

#1121 Fix Windows support by handling `sh` shebangs from pre-commit
  {{cookiecutter.project_name}}/noxfile.py
Labels: bug

#1089 Write documentation in Markdown using MyST
  {{cookiecutter.project_name}}/CODE_OF_CONDUCT.md
  {{cookiecutter.project_name}}/CODE_OF_CONDUCT.rst
  {{cookiecutter.project_name}}/CONTRIBUTING.md
  {{cookiecutter.project_name}}/CONTRIBUTING.rst
  {{cookiecutter.project_name}}/README.md
  {{cookiecutter.project_name}}/README.rst
  {{cookiecutter.project_name}}/docs/codeofconduct.md
  {{cookiecutter.project_name}}/docs/codeofconduct.rst
  {{cookiecutter.project_name}}/docs/conf.py
  {{cookiecutter.project_name}}/docs/contributing.md
  {{cookiecutter.project_name}}/docs/contributing.rst
  {{cookiecutter.project_name}}/docs/index.md
  {{cookiecutter.project_name}}/docs/index.rst
  {{cookiecutter.project_name}}/docs/license.md
  {{cookiecutter.project_name}}/docs/license.rst
  {{cookiecutter.project_name}}/docs/reference.md
  {{cookiecutter.project_name}}/docs/reference.rst
  {{cookiecutter.project_name}}/docs/requirements.txt
  {{cookiecutter.project_name}}/docs/usage.md
  {{cookiecutter.project_name}}/docs/usage.rst
  {{cookiecutter.project_name}}/noxfile.py
  {{cookiecutter.project_name}}/pyproject.toml
  {{cookiecutter.project_name}}/{% if cookiecutter.license == 'Apache-2.0' -%} LICENSE {%- endif %}
  {{cookiecutter.project_name}}/{% if cookiecutter.license == 'Apache-2.0' -%} LICENSE.rst {%- endif %}
  {{cookiecutter.project_name}}/{% if cookiecutter.license == 'GPL-3.0' -%} LICENSE {%- endif %}
  {{cookiecutter.project_name}}/{% if cookiecutter.license == 'GPL-3.0' -%} LICENSE.rst {%- endif %}
  {{cookiecutter.project_name}}/{% if cookiecutter.license == 'MIT' -%} LICENSE {%- endif %}
Labels: documentation

#1133 📚 Update User Guide and README after switch to MyST
  README.rst
  docs/guide.rst
Labels: documentation, cookiecutter

#1135 Add link for contact email in the Code of Conduct
  {{cookiecutter.project_name}}/CODE_OF_CONDUCT.md
Labels: documentation

#1141 Update pre-commit hooks
  .pre-commit-config.yaml
  {{cookiecutter.project_name}}/.pre-commit-config.yaml
Labels: ci, dependencies

#1149 Link license badge to project license
  {{cookiecutter.project_name}}/README.md
  {{cookiecutter.project_name}}/docs/index.md
Labels: documentation

#1160 update COC and add badge
  CODE_OF_CONDUCT.rst
  README.rst
Labels: documentation, cookiecutter
